### PR TITLE
AppImage build script

### PR DESCRIPTION
**Pull request by blipk**
Works for me on latest version of Manjaro.

Needs more testing to find which libraries need to be added to TLPUI.AppDir/usr/lib

### CODE REVIEW

**Comment by mjtueros** [comment]
I can confirm the appimage seems to be working

**Comment by blipk** [comment]
Updated with metadata and icon files

**Comment by d4nj1** [comment]
Hi @blipk and thanks for the contribution. That is awesome!
I have just one small thing to discuss before I would merge the PR.

You added the **appimagetool-x86_64.AppImage** to be already available for the build script. I would prefer to download it on demand if not already available. In that way you can be sure to use the latest version when building. My suggestion would be adding something like this before executing the appimagetool:

```
if [ ! -f appimagetool-x86_64.AppImage ]; then
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
fi
```

I would appreciate your opinion on this.

Kind regards

**Comment by blipk** [comment]
Great idea @d4nj1 
Have pushed an update which does that

**Comment by blipk** [comment]
@d4nj1 is this able to be published on pip3?

Might be better to try this if it is: https://docs.appimage.org/packaging-guide/converting-binary-packages/pkg2appimage.html#converting-python-applications-packaged-with-pip
Can set up a YAML file to run through pkg2appimage that downloads and packages everything.

**Comment by blipk** [comment]
Latest version uses pkg2appimage that pulls tlp-ui from github and pulls dependencies from the debian/ubuntu respositories and packages them into the AppImage, this should work on any system as all the dependencies are there, working on my Manjaro install.

Can be tested here: https://github.com/blipk/TLPUI/blob/master/build/AppImage/out/TLP_UI-x86_64.AppImage

**Comment by blipk** [comment]
@d4nj1 let me know before you merge this, I will change the references in the YAML file to your repository

**Comment by d4nj1** [comment]
Hi @blipk,
sorry for the late response. I just reviewed the last changes and everything seems fine from my point of view. The only thing that would be great is if you could remove the final **build/AppImage/out/TLP_UI-x86_64.AppImage** file from the PR. Then I would merge.

**Comment by blipk** [comment]
No problem @d4nj1 have removed the file and updated the reference in the script to your github.
Thanks.

**Comment by d4nj1** [comment]
Thanks again for your contribution!

**Pull request merged**
