### PR TITLE
Added Portuguese translation from Brazil

### PR DESCRIPTION
**Pull request by tioguda**

### CODE REVIEW

**Comment by d4nj1** [comment]
Thanks a lot for your contribution!
Currently getting someone speaking portuguese for review.

**Comment by bigbruno** [comment]
Portuguese is my native language, i'm readed .po files and think, all is fine.

**Comment by d4nj1** [comment]
@bigbruno Thanks for verifying translation.
I am currently working on some kind of translation validation automation. Please be patient as I am very bussy with personal related stuff. Little time for this project atm.

**Comment by d4nj1** [comment]
Hi @tioguda and @bigbruno ,
sorry to still keep you waiting. I know it has been more than 1.5 years and in software terms that's a lot of time. My next effort on TLPUI goes towards finally adding all waiting translations. So I would be more than happy if you reopen the PR and have a bit more patience with me.
What I would ask you anyway is to remove all **.mo** files as I will recreate them anyway after the review process has been done.

Thanks in advance

**Comment by tioguda** [comment]
No problem brother, there were many changes after my submission, I will wait for your new implementation, and redo the submission if necessary.

Greetings.

**Pull request closed without merging**
