### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by micrococo**

### CODE REVIEW

**Comment by j-e-d** [comment]
I'm not the person that was going to review it, but I speak spanish and it LGTM. Maybe some of the texts need to be updated if original strings changed since Oct/2018.

**Comment by d4nj1** [comment]
I am currently working on some kind of translation validation automation. Please be patient as I am very bussy with personal related stuff. Little time for this project atm.

**Comment by d4nj1** [comment]
Hi @micrococo  and @j-e-d  ,
sorry to still keep you waiting. I know it has been nearly 2 years and in software terms that's a lot of time. My next effort on TLPUI goes towards finally adding all waiting translations.
What I would ask you anyway is to remove all .mo files as I will recreate them anyway after the review process has been done.

Thanks in advance

**Comment by micrococo** [comment]
Done, but now there are conflicts that I don't know how to resolve because I don't know how to use git except the basics.

**Comment by d4nj1** [comment]
Changes have finally been merged here: #80

Thanks a lot for your contribution!

**Pull request closed without merging**
