### PR TITLE
Russian translation: sync with English UI and fix typos

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by d4nj1** [comment]
Hi,
thanks for your contribution. It would be nice if you could remove the .mo files from the PR.

Kind regards

**Comment by dmvolod** [comment]
Hi, @d4nj1 

yes, sure did it. Thanks for review.
Probably @NitroOxid could have a look at this PR also?

**Comment by dmvolod** [comment]
Hi, @d4nj1 
Any updates on this PR?

**Comment by d4nj1** [comment]
Hi @dmvolod ,
will try to get this done next week. As always low on time I still did not manage to move to Weblate. Sorry for taking so long.

**Pull request merged**
