### PR TITLE
Added requirements.txt and steps to install from source in README

### PR DESCRIPTION
**Pull request by PabloCastellano**
Hello. I just discovered your project and found it really useful!

Here is a little contribution. Kudos!

### CODE REVIEW

**Comment by Red-Eyed** [comment]
Is it going to be merged?

**Comment by d4nj1** [comment]
Hi,
due to time issues I was not able to verify this until now. Try to do it in the near future.
What I do not like is the pinned versions in requirements.txt, as this can become outdated at some point of time and it should work with the latest version of the libraries anyway.

Kind regards

**Comment by d4nj1** [comment]
Hi,
maybe my wording was bad. I think we can have a version defined, but it should not be strictly bound to an exact one. So using "**>=**" instead of "**==**" would be ok I in my opinion.

**Comment by PabloCastellano** [comment]
Got it and changed again :+1:

**Comment by d4nj1** [comment]
Hi. I added the instructions to the [Wiki](https://github.com/d4nj1/TLPUI/wiki/Install-instructions) and linked it from the main readme.

Thanks for your contribution!

**Pull request closed without merging**
